
on:
  push:
    branches: [master]

name: Push to Amazon ECR

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_SECRET }}
        aws-region: ${{ secrets.AWS_ECR_LOCATION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: siraj-ai/scraper
        IMAGE_TAG: ${{ github.sha }}
      run:
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
